# fly.toml app configuration file generated for remix-practice-314159 on 2023-06-21T18:00:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-practice-314159"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
