# fly.toml app configuration file generated for remix-jokes-3141 on 2023-06-22T09:41:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remix-jokes-3141"
primary_region = "lhr"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
